""" CS5340/6340 grading script for programming assignment 1 """
"""
This script is only for grading ngrams language models.
How to run:
    python grading.py -gold <correct.trace> -output <system.trace>

[-gold file_path]      path to the correct trace file given to you
[-output file_path]    path to the trace output generated by your system
"""
import sys
import argparse


arg_parser = argparse.ArgumentParser()
arg_parser.add_argument('-gold', type=str, help='Correct output file path')
arg_parser.add_argument('-output', type=str, help='Your output file path')
args = arg_parser.parse_args()

gold = []
output = []
with open(args.gold, 'r') as f:
    for r in f:
        if r.strip():
            gold.append(r.strip())
with open(args.output, 'r') as f:
    for r in f:
        if r.strip():
            output.append(' '.join(r.strip().split()))

print('\nCorrect output file path: '+args.gold)
print('Your output file path: '+args.output)
print('Number of test cases: {:<d}'.format(len(gold)//4))
print('Evaluating...')

accu = 0
for i in range(len(gold) // 4):
    if gold[i*4+1:i*4+4] == output[i*4+1:i*4+4]:
        accu += 1
        print('Test Case {:d} Correct!\n'.format(i))
    else:
        print('Test Case {:d} Wrong'.format(i))
        print('    #### GOLD ####')
        print('\n'.join([' '*4+x for x in gold[i*4+1:i*4+4]]))
        print('    #### OUTPUT ####')
        print('\n'.join([' '*4+x for x in output[i*4+1:i*4+4]]))
        print('')

print('Your system passed {:d}/{:d} cases ({:d}%).'.format(accu, len(gold)//4, int(round(accu*1.0/(len(gold)//4)*100))))

