#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov  3 19:18:43 2019

@author: ritesh
"""

a10_input_sent_w_coref = {
    "0":  "nyt960222.0558",
    "1":  "A3160",
    "2":  "BC-<COREF ID=\"X0\">GROUNDED-JETS</COREF>-BOS",
    "3":  "@amp;LR;",
    "4":  "<COREF ID=\"X1\">02-22</COREF>",
    "5":  "BC-GROUNDED-JETS-BOS",
    "6":  "<COREF ID=\"X2\">NAVY</COREF> GROUNDS F-14'S AFTER <COREF ID=\"X3\">THIRD RECENT CRASH</COREF>",
    "7":  "(For use by New York Times News Service clients)",
    "8":  "By CHRIS BLACK",
    "9":  "c.1996 The Boston Globe",
    "10": "WASHINGTON @amp;MD; The Navy suspended operations for its <COREF ID=\"X4\">entire fleet of F-14 airplanes</COREF> <COREF ID=\"X5\">Thursday</COREF> after the third ``Tomcat'' crash in a month @amp;MD; the second in a week.",
    "11": "<COREF ID=\"X6\">The 72-hour ``safety stand-down''</COREF> came shortly after <COREF ID=\"X7\">an F-14 fighter</COREF> from the USS Nimitz crashed during flight operations in the northern Persian Gulf at about 6:30 a.m. EST.",
    "12": "The Navy announced that <COREF ID=\"X8\">the two Naval aviators on board</COREF> were rescued by a SH-60 helicopter after they ejected from the aircraft.",
    "13": "The Navy said that both men were in good condition.",
    "14": "One aviator suffered minor abrasions.",
    "15": "The Navy is investigating the cause.",
    "16": "Another Tomcat crashed off the coast of California during exercises on the aircraft carrier Carl Vinson on Sunday.",
    "17": "Both crew members were killed.",
    "18": "Late last month, an F-14 crashed near Nashville, killing both crew members and three civilians on the ground.",
    "19": "Although the crash Thursday was the third Tomcat crash this year, <COREF ID=\"X9\">Defense Department spokesman Kenneth Bacon</COREF> said the Navy had uncovered no evidence of a flaw in the aircraft.",
    "20": "<COREF ID=\"X10\">A safety stand-down</COREF> is a procedure the military uses to conduct an intensive review.",
    "21": "During this three-day period, the three classes of F-14s will stay out of the air so Navy personnel can review maintenance procedures and equipment, plus check each aircraft for weaknesses or deficiencies.",
    "22": "The F-14s on the deck of <COREF ID=\"X11\">the USS America</COREF> will be allowed to fly off because the aircraft carrier is returning from a deployment.",
    "23": "<COREF ID=\"X12\">Carrier</COREF> decks are routinely cleared of aircraft the day before the carrier docks.",
    "24": "``We do not know what has caused <COREF ID=\"X13\">these three crashes this year</COREF>,'' Bacon said.",
    "25": "``The goal of the stand-down is to take a time out to look at everything involved with the F-14s.",
    "26": "<COREF ID=\"X14\">Adm. Jeremy Boorda</COREF>, the chief of Naval Operations, informed <COREF ID=\"X15\">Deputy Defense Secretary John White</COREF> of the latest crash Thursday morning and told him he was ordering the standdown for the entire fleet of more than 300 aircraft, Bacon said.",
    "27": "``What the Navy is trying to do is find out what caused these accidents,'' Bacon said.",
    "28": "In the past five years, 32 F-14s have crashed.",
    "29": "<COREF ID=\"X16\">One</COREF> of the Navy's first female pilots, Lt. Kara Hultgren, died while trying to land an F-14 on an aircraft carrier in 1994.",
    "30": "The Navy concluded that engine failure caused that crash.",
    "31": "The Tomcat, a $38 million, twin-engine aircraft built by the Grumman Aerospace Corp., is the standard fighter plane used by the Navy for close-in air combat.",
    "32": "The aircraft has been in operation since 1973.",
    "33": "<COREF ID=\"X17\">The oldest version of the aircraft</COREF>, the F-14A, is scheduled to be phased out by the year 2004.",
    "34": "The crash rate for the F-14 dropped dramatically after <COREF ID=\"X18\">the initial years of deployment</COREF> and has generally gone down since then except for occasional spurts of accidents, according to Naval records.",
    "35": "Bacon said the Navy had no single explanation for the increases in F-14 accidents.",
    "36": "``The Navy informs me that they have been unable to find a common thread to these accidents,'' Bacon said.",
    "37": "``<COREF ID=\"X19\">This</COREF> is a mystery.''",
    "38": "NYT-02-22-96 1924EST"
}

a10_input_sent_wo_coref = {
   "0":  "nyt960222.0558",
   "1":  "A3160",
   "2":  "BC-GROUNDED-JETS-BOS",
   "3":  "@amp;LR;",
   "4":  "02-22",
   "5":  "BC-GROUNDED-JETS-BOS",
   "6":  "NAVY GROUNDS F-14'S AFTER THIRD RECENT CRASH",
   "7":  "(For use by New York Times News Service clients)",
   "8":  "By CHRIS BLACK",
   "9":  "c.1996 The Boston Globe",
   "10": "WASHINGTON @amp;MD; The Navy suspended operations for its entire fleet of F-14 airplanes Thursday after the third ``Tomcat'' crash in a month @amp;MD; the second in a week.",
   "11": "The 72-hour ``safety stand-down'' came shortly after an F-14 fighter from the USS Nimitz crashed during flight operations in the northern Persian Gulf at about 6:30 a.m. EST.",
   "12": "The Navy announced that the two Naval aviators on board were rescued by a SH-60 helicopter after they ejected from the aircraft.",
   "13": "The Navy said that both men were in good condition.",
   "14": "One aviator suffered minor abrasions.",
   "15": "The Navy is investigating the cause.",
   "16": "Another Tomcat crashed off the coast of California during exercises on the aircraft carrier Carl Vinson on Sunday.",
   "17": "Both crew members were killed.",
   "18": "Late last month, an F-14 crashed near Nashville, killing both crew members and three civilians on the ground.",
   "19": "Although the crash Thursday was the third Tomcat crash this year, Defense Department spokesman Kenneth Bacon said the Navy had uncovered no evidence of a flaw in the aircraft.",
   "20": "A safety stand-down is a procedure the military uses to conduct an intensive review.",
   "21": "During this three-day period, the three classes of F-14s will stay out of the air so Navy personnel can review maintenance procedures and equipment, plus check each aircraft for weaknesses or deficiencies.",
   "22": "The F-14s on the deck of the USS America will be allowed to fly off because the aircraft carrier is returning from a deployment.",
   "23": "Carrier decks are routinely cleared of aircraft the day before the carrier docks.",
   "24": "``We do not know what has caused these three crashes this year,'' Bacon said.",
   "25": "``The goal of the stand-down is to take a time out to look at everything involved with the F-14s.",
   "26": "Adm. Jeremy Boorda, the chief of Naval Operations, informed Deputy Defense Secretary John White of the latest crash Thursday morning and told him he was ordering the standdown for the entire fleet of more than 300 aircraft, Bacon said.",
   "27": "``What the Navy is trying to do is find out what caused these accidents,'' Bacon said.",
   "28": "In the past five years, 32 F-14s have crashed.",
   "29": "One of the Navy's first female pilots, Lt. Kara Hultgren, died while trying to land an F-14 on an aircraft carrier in 1994.",
   "30": "The Navy concluded that engine failure caused that crash.",
   "31": "The Tomcat, a $38 million, twin-engine aircraft built by the Grumman Aerospace Corp., is the standard fighter plane used by the Navy for close-in air combat.",
   "32": "The aircraft has been in operation since 1973.",
   "33": "The oldest version of the aircraft, the F-14A, is scheduled to be phased out by the year 2004.",
   "34": "The crash rate for the F-14 dropped dramatically after the initial years of deployment and has generally gone down since then except for occasional spurts of accidents, according to Naval records.",
   "35": "Bacon said the Navy had no single explanation for the increases in F-14 accidents.",
   "36": "``The Navy informs me that they have been unable to find a common thread to these accidents,'' Bacon said.",
   "37": "``This is a mystery.''",
   "38": "NYT-02-22-96 1924EST"
}

a10_corefs = {
        "X0": ("GROUNDED-JETS",'2'),
        "X1": ("02-22",'4'),
        "X2": ("NAVY",'6'),
        "X3": ("THIRD RECENT CRASH",'6'),
        "X4": ("entire fleet of F-14 airplanes",'10'),
        "X5": ("Thursday",'10'),
        "X6": ("The 72-hour ``safety stand-down''",'11'),
        "X7": ("an F-14 fighter",'11'),
        "X8": ("the two Naval aviators on board",'12'),
        "X9": ("Defense Department spokesman Kenneth Bacon",'19'),
        "X10": ("A safety stand-down",'20'),
        "X11": ("the USS America",'22'),
        "X12": ("Carrier",'23'),
        "X13": ("these three crashes this year",'24'),
        "X14": ("Adm. Jeremy Boorda",'26'),
        "X15": ("Deputy Defense Secretary John White",'26'),
        "X16": ("One",'29'),
        "X17": ("The oldest version of the aircraft",'33'),
        "X18": ("the initial years of deployment",'34'),
        "X19": ("This",'37')
}

a10_key_dict = {'X0': {'orig': 'JETS',
                       'corefs': [('5', 'JETS'),
                                  ('21', 'F-14s'),
                                  ('25', 'F-14s')]},
                'X1': {'orig': '02-22',
                       'corefs': [('38', '02-22-96')]},
                'X2': {'orig': 'NAVY',
                       'corefs': [('10', 'Navy'),
                                  ('12', 'Navy'),
                                  ('13', 'Navy'),
                                  ('15', 'Navy'),
                                  ('19', 'Navy'),
                                  ('21', 'Navy'),
                                  ('27', 'Navy'),
                                  ('30', 'Navy'),
                                  ('35', 'Navy'),
                                  ('36', 'Navy'),
                                  ('36', 'they')]},
                'X3': {'orig': 'CRASH',
                       'corefs': [('10', 'crash'),
                                  ('10', 'second'),
                                  ('19', 'crash'),
                                  ('19', 'crash'),
                                  ('26', 'crash')]},
                'X4': {'orig': 'fleet',
                       'corefs': [('26', 'fleet')]},
                'X5': {'orig': 'Thursday',
                       'corefs': [('19', 'Thursday'),
                                  ('26', 'Thursday')]},
                'X6': {'orig': "down",
                       'corefs': [('25', 'stand-down'),
                                  ('26', 'standdown')]},
                'X7': {'orig': 'fighter',
                       'corefs': [('12', 'aircraft'),
                                  ('19', 'the aircraft'),
                                  ('31', 'Tomcat'),
                                  ('31', 'aircraft'),
                                  ('31', 'plane'),
                                  ('32', 'aircraft'),
                                  ('34', 'F-14'),
                                  ('35', 'F-14')]},
                'X8': {'orig': 'aviators',
                       'corefs': [('12', 'they'),
                                  ('13', 'men')]},
                'X9': {'orig': 'Bacon',
                       'corefs': [('24', 'Bacon'),
                                  ('26', 'Bacon'),
                                  ('27', 'Bacon'),
                                  ('35', 'Bacon'),
                                  ('36', 'me'),
                                  ('36', 'Bacon')]},
                'X10': {'orig': 'down',
                        'corefs': [('20', 'procedure'),
                                   ('21', 'period')]},
                'X11': {'orig': 'America',
                        'corefs': [('22', 'carrier')]},
                'X12': {'orig': 'Carrier',
                        'corefs': [('23', 'carrier')]},
                'X13': {'orig': 'crashes',
                        'corefs': [('27', 'accidents'),
                                   ('36', 'accidents')]},
                'X14': {'orig': 'Boorda',
                        'corefs': [('26', 'chief of Naval Operations'),
                                   ('26', 'he')]},
                'X15': {'orig': 'White',
                        'corefs': [('26', 'him')]},
                'X16': {'orig': 'One',
                        'corefs': [('29', 'Kara Hultgren')]},
                'X17': {'orig': 'version',
                        'corefs': [('33', 'F-14A')]},
                'X18': {'orig': 'years',
                        'corefs': [('34', 'then')]},
                'X19': {'orig': 'This',
                        'corefs': [('37', 'mystery')]}}